name: Commit new data files published by Ontario Digial Service

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  commitNewDataFile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install Node.js dependencies
      run: npm ci

    - name: Download the new data file
      id: downloadFile
      run: npm run fetchDataFile

    # Scenarios:
    # 1. When a new file is downloaded, the grep command returns the exit code 1 and causes the step to fail;
    # 2. When a new file is not detected, this step will complete successfully.
    - name: Check if a new file is downloaded
      id: checkDownloads
      continue-on-error: true
      run: |
        git status
        git status | grep "nothing to commit"

    - name: Get the status of the check step
      run: echo "${{ steps.checkDownloads.outcome }}"

    # Only commit and push into the repo when a new file is downloaded
    - name: Commit the new data file and the updated latest.json
      if: steps.checkDownloads.outcome == 'failure'
      run: |
        git config --local user.email "wecount.info@gmail.com"
        git config --local user.name "Auto Update via GitHub Action"
        git add ODC/*
        git commit -m "feat: add a new data file published at https://data.ontario.ca"

    - name: Push changes
      if: steps.checkDownloads.outcome == 'failure'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
